<assembly xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.0 http://maven.apache.org/xsd/assembly-1.1.0.xsd">
    <id><#noparse>${version}</#noparse></id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <fileSets>
        <fileSet>
            <directory><#noparse>${basedir}</#noparse>/src/main/resources</directory>
            <includes>
                <include>plugin.yaml</include>
                <include>frontend.yaml</include>
                <include>setting.json</include>
            </includes>
            <outputDirectory>/</outputDirectory>
        </fileSet>
        <fileSet>
            <directory><#noparse>${basedir}</#noparse>/src/main/resources/sql</directory>
            <includes>
                <include>install.sql</include>
                <include>uninstall.sql</include>
            </includes>
            <outputDirectory>sql</outputDirectory>
        </fileSet>
        <fileSet>
            <directory><#noparse>${basedir}</#noparse>/src/main/resources/ui</directory>
            <outputDirectory>ui</outputDirectory>
        </fileSet>
        <fileSet>
            <directory><#noparse>${project.build.directory}</#noparse>/lib</directory>
            <includes>
                <include>*.jar</include>
            </includes>
            <outputDirectory>lib</outputDirectory>
        </fileSet>
        <fileSet>
            <directory><#noparse>${project.build.directory}</#noparse></directory>
            <includes>
                <include><#noparse>${project.artifactId}</#noparse>.jar</include>
            </includes>
            <outputDirectory>code</outputDirectory>
        </fileSet>
    </fileSets>
</assembly>
