server {
    listen 80;
    listen [::]:80;
    server_name duck.vin;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name duck.vin;

    ssl_certificate     /www/server/panel/vhost/cert/八号球房后台管理/fullchain.pem;
    ssl_certificate_key /www/server/panel/vhost/cert/八号球房后台管理/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000" always;

    root /www/Billiards/dist;
    index index.html index.htm;

    access_log /www/wwwlogs/八号球房后台管理.log;
    error_log  /www/wwwlogs/八号球房后台管理.error.log;

    location /.well-known/ {
        root /www/wwwroot/java_node_ssl;
    }

    location /api/plugin-static/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 30s;
        proxy_read_timeout 86400s;
        proxy_send_timeout 30s;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 30s;
        proxy_read_timeout 86400s;
        proxy_send_timeout 30s;
    }

    location /api/ws/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location /ws/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* /(\.git|\.svn|\.bzr|\.vscode|\.idea|node_modules)/ {
        return 404;
    }

    location ~* (\.env.*|application(-\w+)?\.(ya?ml|properties)|pom\.xml|package(-lock)?\.json|pnpm-lock\.yaml|\.sql(\.gz)?)$ {
        return 404;
    }
}
