version: 4.0.0
# 开发环境配置

spring:
  # 开发环境数据源
  datasource:
    url: jdbc:mysql://localhost:3306/tt_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 30
      maximum-pool-size: 300
      auto-commit: true
      idle-timeout: 600000
      pool-name: tt
      max-lifetime: 1800000
      connection-timeout: 30000
  servlet:
    multipart:
      #实际生产环境需要设置这里方便测试不限制上传文件大小
      max-file-size: -1
      max-request-size: -1
# 开发环境日志级别
logging:
  level:
    root: info
    com.modules: debug
    com.tt: debug
    com.baomidou.mybatis: debug
    org.springframework.web: debug
    org.springframework.security: debug

# 开发环境 Knife4j
knife4j:
  production: false
  enable: true

# 开发环境 Sa-Token
sa-token:
  is-log: true

# 将来考虑缓存切换Redis或者local(本地缓存)
tt:
  cache: local
