version: 4.0.0
server:
  # 服务端口
  port: 8080
spring:
  profiles:
    # 激活环境
    active: "@env@"
  application:
    name: tt-admin
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  config:
    import:
      - classpath:config/druid.yml
      - classpath:config/mybatis-plus.yml
      - classpath:config/swagger.yml
      - classpath:config/sa-token.yml

plugin:
  menu:
    root-name: 插件
    root-icon: mdi:puzzle-outline


