import { computed, nextTick, ref, shallowRef } from 'vue';
import type { RouteRecordRaw } from 'vue-router';
import { defineStore } from 'pinia';
import { useBoolean } from '@sa/hooks';
import type { CustomRoute, ElegantConstRoute, LastLevelRouteKey, RouteKey, RouteMap } from '@elegant-router/types';
import { router } from '@/router';
import { fetchGetConstantRoutes, fetchGetUserRoutes, fetchIsRouteExist, fetchPluginFrontendModules } from '@/service/api';
import importPluginModule from '@/utils/plugin-import/_import';
import BaseLayout from '@/layouts/base-layout/index.vue';
import BlankLayout from '@/layouts/blank-layout/index.vue';
import { mergeLocaleMessages } from '@/locales';
import { useSvgIcon } from '@/hooks/common/icon';
import { SetupStoreId } from '@/enum';
import { createStaticRoutes, getAuthVueRoutes } from '@/router/routes';
import { ROOT_ROUTE } from '@/router/routes/builtin';
import { getRouteName, getRoutePath } from '@/router/elegant/transform';
import { useAuthStore } from '../auth';
import { useDictStore } from '../dict';
import { useTabStore } from '../tab';
import {
  filterAuthRoutesByRoles,
  getBreadcrumbsByRoute,
  getCacheRouteNames,
  getGlobalMenuByBaseRoute,
  getGlobalMenusByAuthRoutes,
  getSelectedMenuKeyPathByKey,
  isRouteExistByRouteName,
  sortRoutesByOrder,
  transformMenuToSearchMenus,
  updateLocaleOfGlobalMenus
} from './shared';

const pluginDevEnabled = import.meta.env.DEV && import.meta.env.VITE_PLUGIN_DEV_SOURCE === 'Y';

export const useRouteStore = defineStore(SetupStoreId.Route, () => {
  const authStore = useAuthStore();
  const tabStore = useTabStore();
  const { bool: isInitConstantRoute, setBool: setIsInitConstantRoute } = useBoolean();
  const { bool: isInitAuthRoute, setBool: setIsInitAuthRoute } = useBoolean();
  const { bool: isInitPluginRoute, setBool: setIsInitPluginRoute } = useBoolean();

  /**
   * Auth route mode
   *
   * It recommends to use static mode in the development environment, and use dynamic mode in the production
   * environment, if use static mode in development environment, the auth routes will be auto generated by plugin
   * "@elegant-router/vue"
   */
  const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE);

  /** Home route key */
  const routeHome = ref(import.meta.env.VITE_ROUTE_HOME);

  /**
   * Set route home
   *
   * @param routeKey Route key
   */
  function setRouteHome(routeKey: LastLevelRouteKey) {
    routeHome.value = routeKey;
  }

  /** constant routes */
  const constantRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addConstantRoutes(routes: ElegantConstRoute[]) {
    const constantRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach(route => {
      constantRoutesMap.set(route.name, route);
    });

    constantRoutes.value = Array.from(constantRoutesMap.values());
  }

  /** auth routes */
  const authRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addAuthRoutes(routes: ElegantConstRoute[]) {
    const authRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach(route => {
      authRoutesMap.set(route.name, route);
    });

    authRoutes.value = Array.from(authRoutesMap.values());
  }

  const removeRouteFns: (() => void)[] = [];
  const pluginRouteRemoveFns: (() => void)[] = [];
  const pluginLocaleLoaded = new Map<string, Set<string>>();
  let pluginRouteRetryCount = 0;
  let pluginRouteRetryTimer: number | null = null;
  let pluginStatusWs: WebSocket | null = null;
  let pluginStatusReconnectTimer: number | null = null;
  let pluginStatusInited = false;
  const pluginLayoutComponents = {
    base: BaseLayout,
    blank: BlankLayout
  } as const;
  type PluginLayoutKey = keyof typeof pluginLayoutComponents;
  const DEFAULT_PLUGIN_LAYOUT: PluginLayoutKey = 'base';

  /** Global menus */
  const menus = ref<App.Global.Menu[]>([]);
  const baseMenus = ref<App.Global.Menu[]>([]);
  const pluginMenus = ref<App.Global.Menu[]>([]);
  const searchMenus = computed(() => transformMenuToSearchMenus(menus.value));

  /** Get global menus */
  function getGlobalMenus(routes: ElegantConstRoute[]) {
    baseMenus.value = getGlobalMenusByAuthRoutes(routes);
    syncMenus();
  }

  /** Update global menus by locale */
  function updateGlobalMenusByLocale() {
    syncMenus();
  }

  function syncMenus() {
    const mergedMenus = mergeMenus(baseMenus.value, pluginMenus.value);
    menus.value = updateLocaleOfGlobalMenus(mergedMenus);
  }

  /** Cache routes */
  const cacheRoutes = ref<RouteKey[]>([]);

  /**
   * Exclude cache routes
   *
   * for reset route cache
   */
  const excludeCacheRoutes = ref<RouteKey[]>([]);

  /**
   * Get cache routes
   *
   * @param routes Vue routes
   */
  function getCacheRoutes(routes: RouteRecordRaw[]) {
    cacheRoutes.value = getCacheRouteNames(routes);
  }

  /**
   * Reset route cache
   *
   * @default router.currentRoute.value.name current route name
   * @param routeKey
   */
  async function resetRouteCache(routeKey?: RouteKey) {
    const routeName = routeKey || (router.currentRoute.value.name as RouteKey);

    excludeCacheRoutes.value.push(routeName);

    await nextTick();

    excludeCacheRoutes.value = [];
  }

  /** Global breadcrumbs */
  const breadcrumbs = computed(() => getBreadcrumbsByRoute(router.currentRoute.value, menus.value));

  /** Reset store */
  async function resetStore() {
    const routeStore = useRouteStore();

    routeStore.$reset();

    stopPluginStatusWatcher();
    resetVueRoutes();
    resetPluginRoutes();
    baseMenus.value = [];
    pluginMenus.value = [];
    setIsInitPluginRoute(false);
    syncMenus();

    // after reset store, need to re-init constant route
    await initConstantRoute();
  }

  /** Reset vue routes */
  function resetVueRoutes() {
    removeRouteFns.forEach(fn => fn());
    removeRouteFns.length = 0;
  }

  function resetPluginRoutes() {
    pluginRouteRemoveFns.forEach(fn => fn());
    pluginRouteRemoveFns.length = 0;
    pluginMenus.value = [];
    cacheRoutes.value = cacheRoutes.value.filter(name => !String(name).startsWith('plugin-')) as RouteKey[];
    pluginLocaleLoaded.clear();
    syncMenus();
  }

  function buildPluginStatusWsUrl() {
    const protocol = window.location.protocol === 'https:' ? 'wss' : 'ws';
    const proxyPrefix = import.meta.env.DEV ? '/proxy-default' : '';
    return `${protocol}://${window.location.host}${proxyPrefix}/ws/plugin/status`;
  }

  function initPluginStatusWatcher() {
    if (pluginStatusInited) return;
    pluginStatusInited = true;
    connectPluginStatusWs();
  }

  function connectPluginStatusWs() {
    if (pluginStatusWs) {
      pluginStatusWs.close();
    }
    const ws = new WebSocket(buildPluginStatusWsUrl());
    pluginStatusWs = ws;
    ws.onopen = async () => {
      if (!authStore.userInfo.userId) {
        return;
      }
      const dictStore = useDictStore();
      await dictStore.init(true);
      await refreshPluginRoutes();
    };
    ws.onmessage = async event => {
      try {
        const payload = JSON.parse(event.data);
        const status = String(payload?.status || '').toUpperCase();
        const action = String(payload?.action || '').toUpperCase();
        if (action === 'SYSTEM_READY' && status === 'SUCCESS') {
          const dictStore = useDictStore();
          await dictStore.init(true);
          await refreshPluginRoutes();
          return;
        }
        if (status === 'SUCCESS') {
          await refreshPluginRoutes();
        }
      } catch (error) {
        console.error('[plugin] websocket message parse failed:', error);
      }
    };
    ws.onclose = () => {
      if (pluginStatusReconnectTimer) window.clearTimeout(pluginStatusReconnectTimer);
      pluginStatusReconnectTimer = window.setTimeout(connectPluginStatusWs, 2000);
    };
    ws.onerror = () => {
      ws.close();
    };
  }

  function stopPluginStatusWatcher() {
    if (pluginStatusReconnectTimer) {
      window.clearTimeout(pluginStatusReconnectTimer);
      pluginStatusReconnectTimer = null;
    }
    if (pluginStatusWs) {
      pluginStatusWs.close();
      pluginStatusWs = null;
    }
    pluginStatusInited = false;
  }

  /** init constant route */
  async function initConstantRoute() {
    if (isInitConstantRoute.value) return;

    const staticRoute = createStaticRoutes();

    if (authRouteMode.value === 'static') {
      addConstantRoutes(staticRoute.constantRoutes);
    } else {
      const { data, error } = await fetchGetConstantRoutes();

      if (!error) {
        addConstantRoutes(data);
      } else {
        // if fetch constant routes failed, use static constant routes
        addConstantRoutes(staticRoute.constantRoutes);
      }
    }

    handleConstantAndAuthRoutes();

    setIsInitConstantRoute(true);

    tabStore.initHomeTab();
  }

  /** Init auth route */
  async function initAuthRoute() {
    // check if user info is initialized
    if (!authStore.userInfo.userId) {
      await authStore.initUserInfo();
    }
    if (!authStore.userInfo.userId) {
      return;
    }

    if (authRouteMode.value === 'static') {
      initStaticAuthRoute();
    } else {
      await initDynamicAuthRoute();
    }

    await initPluginRoutes();
    initPluginStatusWatcher();

    tabStore.initHomeTab();
  }

  /** Init plugin routes */
  async function initPluginRoutes(forceReload = false) {
    if (isInitPluginRoute.value && !forceReload) return;

    const { data, error } = await fetchPluginFrontendModules();

    if (error) {
      setIsInitPluginRoute(false);
      schedulePluginRouteRetry();
      return;
    }

    const modules = data ?? [];
    if (!modules.length && pluginRouteRetryCount < 5) {
      setIsInitPluginRoute(false);
      schedulePluginRouteRetry();
      return;
    }

    const cacheBuster = forceReload ? String(Date.now()) : '';
    await applyPluginModules(modules, cacheBuster);
    setIsInitPluginRoute(true);
    resetPluginRouteRetry();
  }

  function schedulePluginRouteRetry() {
    if (pluginRouteRetryCount >= 5 || pluginRouteRetryTimer !== null) {
      return;
    }
    pluginRouteRetryCount += 1;
    pluginRouteRetryTimer = window.setTimeout(async () => {
      pluginRouteRetryTimer = null;
      await initPluginRoutes(true);
    }, 1500);
  }

  function resetPluginRouteRetry() {
    pluginRouteRetryCount = 0;
    if (pluginRouteRetryTimer !== null) {
      window.clearTimeout(pluginRouteRetryTimer);
      pluginRouteRetryTimer = null;
    }
  }

  /** Force refresh plugin routes and menus */
  async function refreshPluginRoutes() {
    setIsInitPluginRoute(false);
    await initPluginRoutes(true);
  }

  /** Init static auth route */
  function initStaticAuthRoute() {
    const { authRoutes: staticAuthRoutes } = createStaticRoutes();

    if (authStore.isStaticSuper) {
      addAuthRoutes(staticAuthRoutes);
    } else {
      const filteredAuthRoutes = filterAuthRoutesByRoles(staticAuthRoutes, authStore.userInfo.roles);

      addAuthRoutes(filteredAuthRoutes);
    }

    handleConstantAndAuthRoutes();

    setIsInitAuthRoute(true);
  }

  /** Init dynamic auth route */
  async function initDynamicAuthRoute() {
    const { data, error } = await fetchGetUserRoutes();

    if (!error) {
      const { routes, home } = data;

      addAuthRoutes(routes);

      handleConstantAndAuthRoutes();

      setRouteHome(home);

      handleUpdateRootRouteRedirect(home);

      setIsInitAuthRoute(true);
    } else {
      // if fetch user routes failed, reset store
      authStore.resetStore();
    }
  }

  /** handle constant and auth routes */
  function handleConstantAndAuthRoutes() {
    const allRoutes = [...constantRoutes.value, ...authRoutes.value];

    const sortRoutes = sortRoutesByOrder(allRoutes);

    const vueRoutes = getAuthVueRoutes(sortRoutes);

    resetVueRoutes();

    addRoutesToVueRouter(vueRoutes);

    getGlobalMenus(sortRoutes);

    getCacheRoutes(vueRoutes);
  }

  /**
   * Add routes to vue router
   *
   * @param routes Vue routes
   */
  function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
    routes.forEach(route => {
      const removeFn = router.addRoute(route);
      addRemoveRouteFn(removeFn);
    });
  }

  /**
   * Add remove route fn
   *
   * @param fn
   */
  function addRemoveRouteFn(fn: () => void) {
    removeRouteFns.push(fn);
  }

  /**
   * Update root route redirect when auth route mode is dynamic
   *
   * @param redirectKey Redirect route key
   */
  function handleUpdateRootRouteRedirect(redirectKey: LastLevelRouteKey) {
    const redirect = getRoutePath(redirectKey);

    if (redirect) {
      const rootRoute: CustomRoute = { ...ROOT_ROUTE, redirect };

      router.removeRoute(rootRoute.name);

      const [rootVueRoute] = getAuthVueRoutes([rootRoute]);

      router.addRoute(rootVueRoute);
    }
  }

  /**
   * Get is auth route exist
   *
   * @param routePath Route path
   */
  async function getIsAuthRouteExist(routePath: RouteMap[RouteKey]) {
    const routeName = getRouteName(routePath);

    if (!routeName) {
      return false;
    }

    if (authRouteMode.value === 'static') {
      const { authRoutes: staticAuthRoutes } = createStaticRoutes();
      return isRouteExistByRouteName(routeName, staticAuthRoutes);
    }

    const { data } = await fetchIsRouteExist(routeName);

    return data;
  }

  /**
   * Get selected menu key path
   *
   * @param selectedKey Selected menu key
   */
  function getSelectedMenuKeyPath(selectedKey: string) {
    return getSelectedMenuKeyPathByKey(selectedKey, menus.value);
  }

  async function onRouteSwitchWhenLoggedIn() {
    // some global init logic when logged in and switch route
  }

  async function onRouteSwitchWhenNotLoggedIn() {
    // some global init logic if it does not need to be logged in
  }

  async function applyPluginModules(modules: Api.Plugin.PluginFrontendModule[], cacheBuster = '') {
    resetPluginRoutes();

    if (!modules.length) {
      syncMenus();
      return;
    }

    const pluginMenuList: App.Global.Menu[] = [];
    const cacheNameSet = new Set<RouteKey>(cacheRoutes.value);

    await Promise.all(
      modules.map(async module => {
        if (!module.moduleName) return;
        const moduleInfo = {
          moduleName: module.moduleName,
          pluginId: module.pluginId,
          pluginVersion: buildPluginVersionToken(module.pluginVersion, cacheBuster),
          pluginIsDev: module.pluginIsDev,
          frontDevAddress: module.frontDevAddress
        };
        try {
          await registerPluginLocales(moduleInfo, module.i18n);
          const moduleRouters =
            module.renderer?.toLowerCase() === 'iframe'
              ? createIframeModuleRoutes(module)
              : (await importPluginModule(moduleInfo, module.moduleName)).router(module.routes || [], module.moduleName);
          const routeMap = new Map<string, RouteRecordRaw>();

          moduleRouters.forEach(routeRecord => {
            const { wrapperRoute, viewRoute, fullPath } = buildPluginRoute(routeRecord);
            const removeFn = router.addRoute(wrapperRoute);
            pluginRouteRemoveFns.push(removeFn);

            if (viewRoute?.name && viewRoute.meta?.keepAlive) {
              cacheNameSet.add(viewRoute.name as RouteKey);
            }

            if (viewRoute?.name) {
              const menuRoute: RouteRecordRaw = { ...viewRoute, path: fullPath };
              routeMap.set(String(viewRoute.name), menuRoute);
            }
          });

          module.menus?.forEach(menu => {
            const matchedRoute = routeMap.get(menu.routeName);
            const menuNode = createPluginMenuNode(matchedRoute, menu);
            if (menuNode) {
              pluginMenuList.push(menuNode);
            }
          });
        } catch (error) {
          console.error('[plugin] load module failed:', module.moduleName, error);
        }
      })
    );

    cacheRoutes.value = Array.from(cacheNameSet);
    pluginMenus.value = pluginMenuList;
    syncMenus();
  }

  function buildPluginVersionToken(version?: string | null, cacheBuster = '') {
    const cleanVersion = (version || '').trim();
    const cleanBuster = cacheBuster.trim();
    if (!cleanVersion) return cleanBuster;
    if (!cleanBuster) return cleanVersion;
    return `${cleanVersion}-${cleanBuster}`;
  }

  function createIframeModuleRoutes(module: Api.Plugin.PluginFrontendModule) {
    const routes = module.routes || [];

    return routes.map(routeItem => {
      const routePath = routeItem.path?.startsWith('/') ? routeItem.path : `/${routeItem.path || ''}`;
      const iframeSrc = resolvePluginIframeUrl(module, routePath);

      return {
        name: routeItem.componentName || routeItem.name,
        path: routePath,
        component: () => import('@/views/_builtin/iframe-page/[url].vue'),
        props: {
          url: iframeSrc
        },
        meta: {
          moduleName: module.moduleName,
          title: routeItem.meta?.title || routeItem.name,
          keepAlive: routeItem.meta?.keepAlive ?? false,
          ...(routeItem.meta || {})
        }
      } as RouteRecordRaw;
    });
  }

  function resolvePluginIframeUrl(module: Api.Plugin.PluginFrontendModule, routePath: string) {
    const routeSegment = routePath.startsWith('/') ? routePath : `/${routePath}`;

    if (module.pluginIsDev && pluginDevEnabled) {
      const externalBase = module.frontDevAddress?.trim();
      if (externalBase) {
        const normalizedBase = externalBase.replace(/\/$/, '');
        if (normalizedBase.includes('#')) {
          return `${normalizedBase}${routeSegment}`;
        }
        return `${normalizedBase}/#${routeSegment}`;
      }
    }

    const version = module.pluginVersion ? encodeURIComponent(module.pluginVersion) : '';
    const suffix = version ? `?v=${version}` : '';

    return `/api/plugin-static/${module.pluginId}/index.html${suffix}#${routeSegment}`;
  }

  let pluginRouteSequence = 0;

  function buildPluginRoute(routeRecord: RouteRecordRaw) {
    const baseName = typeof routeRecord.name === 'string' ? routeRecord.name : `plugin-route-${pluginRouteSequence++}`;
    const layoutKey = (routeRecord.meta?.layout as PluginLayoutKey) || DEFAULT_PLUGIN_LAYOUT;
    const layoutComponent = pluginLayoutComponents[layoutKey] ?? pluginLayoutComponents[DEFAULT_PLUGIN_LAYOUT];
    const fullPath = routeRecord.path || `/${baseName}`;

    const viewRoute: RouteRecordRaw = {
      ...routeRecord,
      path: '',
      meta: {
        ...routeRecord.meta,
        layout: layoutKey
      }
    };

    const wrapperRoute: RouteRecordRaw = {
      path: fullPath,
      name: `${baseName}__layout`,
      component: layoutComponent,
      meta: {
        ...(routeRecord.meta || {}),
        layout: layoutKey
      },
      children: [viewRoute]
    };

    return { wrapperRoute, viewRoute, fullPath };
  }

  function createPluginMenuNode(route: RouteRecordRaw | undefined, menuConfig: Api.Plugin.PluginFrontendMenu) {
    if (!route?.name) {
      return null;
    }

    const { SvgIconVNode } = useSvgIcon();
    const menu = getGlobalMenuByBaseRoute({
      name: route.name as RouteKey,
      path: route.path || '',
      meta: route.meta ?? {}
    } as ElegantConstRoute);

    if (menuConfig?.title) {
      menu.label = menuConfig.title;
    }
    if (menuConfig?.i18nKey) {
      menu.i18nKey = menuConfig.i18nKey;
    }
    if (menuConfig?.icon) {
      const useLocalIcon = menuConfig.iconType === '2';
      menu.icon = SvgIconVNode({
        icon: useLocalIcon ? undefined : menuConfig.icon,
        localIcon: useLocalIcon ? menuConfig.icon : undefined,
        fontSize: 20
      });
    }
    menu.order = menuConfig?.order ?? menu.order ?? 0;
    const configuredParentKey = menuConfig?.parent?.trim();
    menu.parentKey = configuredParentKey ? configuredParentKey : null;

    return menu;
  }

  function mergeMenus(baseMenuList: App.Global.Menu[], pluginMenuList: App.Global.Menu[]) {
    const clonedMenus = cloneMenus(baseMenuList);
    pluginMenuList.forEach(menu => insertMenuNode(clonedMenus, menu));
    return sortMenuTree(clonedMenus);
  }

  function cloneMenus(source: App.Global.Menu[]): App.Global.Menu[] {
    return source.map(menu => ({
      ...menu,
      children: menu.children ? cloneMenus(menu.children) : undefined
    }));
  }

  function updateMenuIcon(params: { routeName?: string; routePath?: string; icon?: string | null; iconType?: string | null }) {
    const { routeName, routePath, icon, iconType } = params || {};
    if (!routeName && !routePath) return;
    const { SvgIconVNode } = useSvgIcon();
    const useLocalIcon = String(iconType) === '2';
    const iconVNode = SvgIconVNode({
      icon: useLocalIcon ? undefined : icon || undefined,
      localIcon: useLocalIcon ? icon || undefined : undefined,
      fontSize: 20
    });

    function walk(list: App.Global.Menu[] | undefined) {
      if (!list || list.length === 0) return false;
      for (const item of list) {
        if ((routeName && item.key === routeName) || (routePath && item.routePath === routePath)) {
          item.icon = iconVNode;
          return true;
        }
        if (item.children?.length && walk(item.children)) {
          return true;
        }
      }
      return false;
    }

    const updatedBase = walk(baseMenus.value);
    const updatedPlugin = walk(pluginMenus.value);
    if (updatedBase || updatedPlugin) {
      syncMenus();
    }
  }

  function insertMenuNode(tree: App.Global.Menu[], menuNode: App.Global.Menu) {
    const node: App.Global.Menu = {
      ...menuNode,
      children: menuNode.children ? cloneMenus(menuNode.children) : undefined
    };

    if (!menuNode.parentKey) {
      upsertMenuNode(tree, node);
      return;
    }

    const parent = findMenuByKey(tree, menuNode.parentKey);
    if (parent) {
      parent.children = parent.children || [];
      upsertMenuNode(parent.children, { ...node, parentKey: undefined });
      return;
    }

    upsertMenuNode(tree, node);
  }

  function upsertMenuNode(tree: App.Global.Menu[], candidate: App.Global.Menu) {
    const existing = tree.find(menu => menu.key === candidate.key);
    if (existing) {
      mergeMenuNode(existing, candidate);
    } else {
      tree.push(candidate);
    }
  }

  function mergeMenuNode(target: App.Global.Menu, source: App.Global.Menu) {
    target.label = source.label ?? target.label;
    target.i18nKey = source.i18nKey ?? target.i18nKey;
    target.icon = source.icon ?? target.icon;
    target.order = source.order ?? target.order;
    target.routeName = source.routeName ?? target.routeName;
    if (source.children?.length) {
      target.children = target.children || [];
      source.children.forEach(child => insertMenuNode(target.children!, { ...child, parentKey: undefined }));
    }
  }

  function findMenuByKey(tree: App.Global.Menu[], key: string) {
    for (const menu of tree) {
      if (menu.key === key) {
        return menu;
      }
      if (menu.children?.length) {
        const found = findMenuByKey(menu.children, key);
        if (found) {
          return found;
        }
      }
    }
    return null;
  }

  function sortMenuTree(tree: App.Global.Menu[]) {
    return tree
      .slice()
      .sort((next, prev) => (Number(next.order) || 0) - (Number(prev.order) || 0))
      .map(menu => ({
        ...menu,
        children: menu.children ? sortMenuTree(menu.children) : undefined
      }));
  }


  async function registerPluginLocales(
    moduleInfo: {
      pluginId?: string;
      pluginVersion?: string;
      pluginIsDev?: boolean;
      frontDevAddress?: string;
    },
    localeMap?: Record<string, string>
  ) {
    if (!moduleInfo.pluginId || !localeMap) return;
    const entries = Object.entries(localeMap).filter(([, filePath]) => Boolean(filePath));
    if (!entries.length) return;

    const loadedLocales = pluginLocaleLoaded.get(moduleInfo.pluginId) ?? new Set<string>();

    await Promise.all(
      entries.map(async ([locale, filePath]) => {
        const localeAliases = getLocaleAliases(locale);
        if (localeAliases.every(alias => loadedLocales.has(alias))) {
          return;
        }
        try {
          const urls = resolvePluginAssetUrls(moduleInfo, filePath);
          if (!urls.length) return;

          let messages: Record<string, any> | null = null;
          let loadedUrl = '';

          for (const url of urls) {
            const json = await tryLoadLocaleJson(url);
            if (json) {
              messages = json;
              loadedUrl = url;
              break;
            }
          }

          if (!messages) {
            throw new Error(`No valid locale json found: ${urls.join(', ')}`);
          }

          localeAliases.forEach(alias => {
            mergeLocaleMessages(alias, messages);
            loadedLocales.add(alias);
          });

          if (import.meta.env.DEV) {
            console.debug('[plugin] locale loaded:', moduleInfo.pluginId, locale, loadedUrl);
          }
        } catch (error) {
          console.error('[plugin] load i18n failed:', moduleInfo.pluginId, locale, error);
        }
      })
    );

    pluginLocaleLoaded.set(moduleInfo.pluginId, loadedLocales);
  }

  async function tryLoadLocaleJson(url: string) {
    try {
      const response = await fetch(url, { cache: 'no-store' });
      if (!response.ok) {
        return null;
      }

      const contentType = (response.headers.get('content-type') || '').toLowerCase();
      const text = await response.text();
      const trimmed = text.trim();

      if (!trimmed) {
        return null;
      }

      const maybeJson = contentType.includes('json') || trimmed.startsWith('{') || trimmed.startsWith('[');
      if (!maybeJson) {
        return null;
      }

      return JSON.parse(trimmed) as Record<string, any>;
    } catch {
      return null;
    }
  }

  function resolvePluginAssetUrls(
    moduleInfo: {
      pluginId?: string;
      pluginVersion?: string;
      pluginIsDev?: boolean;
      frontDevAddress?: string;
    },
    assetPath: string
  ) {
    if (!moduleInfo.pluginId || !assetPath) return [] as string[];
    if (/^https?:\/\//i.test(assetPath)) {
      return [assetPath];
    }
    const sanitizedPath = assetPath.replace(/^\/+/, '');
    if (moduleInfo.pluginIsDev && pluginDevEnabled) {
      // 开发态统一走主应用的 /plugin-dev 代理，避免跨域与 CORS。
      const devPath = sanitizedPath.startsWith('src/') ? sanitizedPath : `src/${sanitizedPath}`;
     const hostBase = `/plugin-dev/${moduleInfo.pluginId}`;
      const candidates = new Set<string>();

      candidates.add(`${hostBase}/${sanitizedPath}`);
      candidates.add(`${hostBase}/${devPath}`);

      if (!sanitizedPath.startsWith('public/') && !sanitizedPath.startsWith('src/')) {
        candidates.add(`${hostBase}/public/${sanitizedPath}`);
        candidates.add(`${hostBase}/src/${sanitizedPath}`);
      }

      const externalBase = moduleInfo.frontDevAddress?.trim()?.replace(/\/$/, '');
      if (externalBase) {
        candidates.add(`${externalBase}/${sanitizedPath}`);
        candidates.add(`${externalBase}/${devPath}`);
        if (!sanitizedPath.startsWith('public/') && !sanitizedPath.startsWith('src/')) {
          candidates.add(`${externalBase}/public/${sanitizedPath}`);
          candidates.add(`${externalBase}/src/${sanitizedPath}`);
        }
      }

      return Array.from(candidates);
    }

    const version = moduleInfo.pluginVersion ? encodeURIComponent(moduleInfo.pluginVersion) : '';
    const suffix = version ? `?v=${version}` : '';
    return [`/api/plugin-static/${moduleInfo.pluginId}/${sanitizedPath}${suffix}`];
  }

  function getLocaleAliases(locale: string) {
    const normalized = locale.trim();
    const lower = normalized.toLowerCase();

    if (lower === 'zh-cn') {
      return ['zh-CN', 'zh'];
    }

    if (lower === 'en-us') {
      return ['en-US', 'en'];
    }

    if (lower === 'zh') {
      return ['zh', 'zh-CN'];
    }

    if (lower === 'en') {
      return ['en', 'en-US'];
    }

    return [normalized];
  }

  return {
    resetStore,
    routeHome,
    menus,
    searchMenus,
    updateGlobalMenusByLocale,
    cacheRoutes,
    excludeCacheRoutes,
    resetRouteCache,
    breadcrumbs,
    initConstantRoute,
    isInitConstantRoute,
    initAuthRoute,
    isInitAuthRoute,
    setIsInitAuthRoute,
    refreshPluginRoutes,
    updateMenuIcon,
    getIsAuthRouteExist,
    getSelectedMenuKeyPath,
    onRouteSwitchWhenLoggedIn,
    onRouteSwitchWhenNotLoggedIn
  };
});
