import { computed, nextTick, ref, shallowRef } from 'vue';
import type { RouteRecordRaw } from 'vue-router';
import { defineStore } from 'pinia';
import { useBoolean } from '@sa/hooks';
import type { CustomRoute, ElegantConstRoute, LastLevelRouteKey, RouteKey, RouteMap } from '@elegant-router/types';
import { router } from '@/router';
import { fetchGetConstantRoutes, fetchGetUserRoutes, fetchIsRouteExist, fetchPluginFrontendModules } from '@/service/api';
import importPluginModule from '@/utils/plugin-import/_import';
import BaseLayout from '@/layouts/base-layout/index.vue';
import BlankLayout from '@/layouts/blank-layout/index.vue';
import { mergeLocaleMessages } from '@/locales';
import { SetupStoreId } from '@/enum';
import { createStaticRoutes, getAuthVueRoutes } from '@/router/routes';
import { ROOT_ROUTE } from '@/router/routes/builtin';
import { getRouteName, getRoutePath } from '@/router/elegant/transform';
import { useAuthStore } from '../auth';
import { useTabStore } from '../tab';
import {
  filterAuthRoutesByRoles,
  getBreadcrumbsByRoute,
  getCacheRouteNames,
  getGlobalMenuByBaseRoute,
  getGlobalMenusByAuthRoutes,
  getSelectedMenuKeyPathByKey,
  isRouteExistByRouteName,
  sortRoutesByOrder,
  transformMenuToSearchMenus,
  updateLocaleOfGlobalMenus
} from './shared';

export const useRouteStore = defineStore(SetupStoreId.Route, () => {
  const authStore = useAuthStore();
  const tabStore = useTabStore();
  const { bool: isInitConstantRoute, setBool: setIsInitConstantRoute } = useBoolean();
  const { bool: isInitAuthRoute, setBool: setIsInitAuthRoute } = useBoolean();
  const { bool: isInitPluginRoute, setBool: setIsInitPluginRoute } = useBoolean();

  /**
   * Auth route mode
   *
   * It recommends to use static mode in the development environment, and use dynamic mode in the production
   * environment, if use static mode in development environment, the auth routes will be auto generated by plugin
   * "@elegant-router/vue"
   */
  const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE);

  /** Home route key */
  const routeHome = ref(import.meta.env.VITE_ROUTE_HOME);

  /**
   * Set route home
   *
   * @param routeKey Route key
   */
  function setRouteHome(routeKey: LastLevelRouteKey) {
    routeHome.value = routeKey;
  }

  /** constant routes */
  const constantRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addConstantRoutes(routes: ElegantConstRoute[]) {
    const constantRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach(route => {
      constantRoutesMap.set(route.name, route);
    });

    constantRoutes.value = Array.from(constantRoutesMap.values());
  }

  /** auth routes */
  const authRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addAuthRoutes(routes: ElegantConstRoute[]) {
    const authRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach(route => {
      authRoutesMap.set(route.name, route);
    });

    authRoutes.value = Array.from(authRoutesMap.values());
  }

  const removeRouteFns: (() => void)[] = [];
  const pluginRouteRemoveFns: (() => void)[] = [];
  const pluginLocaleLoaded = new Map<string, Set<string>>();
  const pluginLayoutComponents = {
    base: BaseLayout,
    blank: BlankLayout
  } as const;
  type PluginLayoutKey = keyof typeof pluginLayoutComponents;
  const DEFAULT_PLUGIN_LAYOUT: PluginLayoutKey = 'base';

  /** Global menus */
  const menus = ref<App.Global.Menu[]>([]);
  const baseMenus = ref<App.Global.Menu[]>([]);
  const pluginMenus = ref<App.Global.Menu[]>([]);
  const searchMenus = computed(() => transformMenuToSearchMenus(menus.value));

  /** Get global menus */
  function getGlobalMenus(routes: ElegantConstRoute[]) {
    baseMenus.value = getGlobalMenusByAuthRoutes(routes);
    syncMenus();
  }

  /** Update global menus by locale */
  function updateGlobalMenusByLocale() {
    syncMenus();
  }

  function syncMenus() {
    const mergedMenus = mergeMenus(baseMenus.value, pluginMenus.value);
    menus.value = updateLocaleOfGlobalMenus(mergedMenus);
  }

  /** Cache routes */
  const cacheRoutes = ref<RouteKey[]>([]);

  /**
   * Exclude cache routes
   *
   * for reset route cache
   */
  const excludeCacheRoutes = ref<RouteKey[]>([]);

  /**
   * Get cache routes
   *
   * @param routes Vue routes
   */
  function getCacheRoutes(routes: RouteRecordRaw[]) {
    cacheRoutes.value = getCacheRouteNames(routes);
  }

  /**
   * Reset route cache
   *
   * @default router.currentRoute.value.name current route name
   * @param routeKey
   */
  async function resetRouteCache(routeKey?: RouteKey) {
    const routeName = routeKey || (router.currentRoute.value.name as RouteKey);

    excludeCacheRoutes.value.push(routeName);

    await nextTick();

    excludeCacheRoutes.value = [];
  }

  /** Global breadcrumbs */
  const breadcrumbs = computed(() => getBreadcrumbsByRoute(router.currentRoute.value, menus.value));

  /** Reset store */
  async function resetStore() {
    const routeStore = useRouteStore();

    routeStore.$reset();

    resetVueRoutes();
    resetPluginRoutes();
    baseMenus.value = [];
    pluginMenus.value = [];
    setIsInitPluginRoute(false);
    syncMenus();

    // after reset store, need to re-init constant route
    await initConstantRoute();
  }

  /** Reset vue routes */
  function resetVueRoutes() {
    removeRouteFns.forEach(fn => fn());
    removeRouteFns.length = 0;
  }

  function resetPluginRoutes() {
    pluginRouteRemoveFns.forEach(fn => fn());
    pluginRouteRemoveFns.length = 0;
    pluginMenus.value = [];
    cacheRoutes.value = cacheRoutes.value.filter(name => !String(name).startsWith('plugin-')) as RouteKey[];
    pluginLocaleLoaded.clear();
    syncMenus();
  }

  /** init constant route */
  async function initConstantRoute() {
    if (isInitConstantRoute.value) return;

    const staticRoute = createStaticRoutes();

    if (authRouteMode.value === 'static') {
      addConstantRoutes(staticRoute.constantRoutes);
    } else {
      const { data, error } = await fetchGetConstantRoutes();

      if (!error) {
        addConstantRoutes(data);
      } else {
        // if fetch constant routes failed, use static constant routes
        addConstantRoutes(staticRoute.constantRoutes);
      }
    }

    handleConstantAndAuthRoutes();

    setIsInitConstantRoute(true);

    tabStore.initHomeTab();
  }

  /** Init auth route */
  async function initAuthRoute() {
    // check if user info is initialized
    if (!authStore.userInfo.userId) {
      await authStore.initUserInfo();
    }

    if (authRouteMode.value === 'static') {
      initStaticAuthRoute();
    } else {
      await initDynamicAuthRoute();
    }

    await initPluginRoutes();

    tabStore.initHomeTab();
  }

  /** Init plugin routes */
  async function initPluginRoutes(forceReload = false) {
    if (isInitPluginRoute.value && !forceReload) return;

    const { data, error } = await fetchPluginFrontendModules();

    if (!error) {
      await applyPluginModules(data ?? []);
    }

    setIsInitPluginRoute(true);
  }

  /** Force refresh plugin routes and menus */
  async function refreshPluginRoutes() {
    setIsInitPluginRoute(false);
    await initPluginRoutes(true);
  }

  /** Init static auth route */
  function initStaticAuthRoute() {
    const { authRoutes: staticAuthRoutes } = createStaticRoutes();

    if (authStore.isStaticSuper) {
      addAuthRoutes(staticAuthRoutes);
    } else {
      const filteredAuthRoutes = filterAuthRoutesByRoles(staticAuthRoutes, authStore.userInfo.roles);

      addAuthRoutes(filteredAuthRoutes);
    }

    handleConstantAndAuthRoutes();

    setIsInitAuthRoute(true);
  }

  /** Init dynamic auth route */
  async function initDynamicAuthRoute() {
    const { data, error } = await fetchGetUserRoutes();

    if (!error) {
      const { routes, home } = data;

      addAuthRoutes(routes);

      handleConstantAndAuthRoutes();

      setRouteHome(home);

      handleUpdateRootRouteRedirect(home);

      setIsInitAuthRoute(true);
    } else {
      // if fetch user routes failed, reset store
      authStore.resetStore();
    }
  }

  /** handle constant and auth routes */
  function handleConstantAndAuthRoutes() {
    const allRoutes = [...constantRoutes.value, ...authRoutes.value];

    const sortRoutes = sortRoutesByOrder(allRoutes);

    const vueRoutes = getAuthVueRoutes(sortRoutes);

    resetVueRoutes();

    addRoutesToVueRouter(vueRoutes);

    getGlobalMenus(sortRoutes);

    getCacheRoutes(vueRoutes);
  }

  /**
   * Add routes to vue router
   *
   * @param routes Vue routes
   */
  function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
    routes.forEach(route => {
      const removeFn = router.addRoute(route);
      addRemoveRouteFn(removeFn);
    });
  }

  /**
   * Add remove route fn
   *
   * @param fn
   */
  function addRemoveRouteFn(fn: () => void) {
    removeRouteFns.push(fn);
  }

  /**
   * Update root route redirect when auth route mode is dynamic
   *
   * @param redirectKey Redirect route key
   */
  function handleUpdateRootRouteRedirect(redirectKey: LastLevelRouteKey) {
    const redirect = getRoutePath(redirectKey);

    if (redirect) {
      const rootRoute: CustomRoute = { ...ROOT_ROUTE, redirect };

      router.removeRoute(rootRoute.name);

      const [rootVueRoute] = getAuthVueRoutes([rootRoute]);

      router.addRoute(rootVueRoute);
    }
  }

  /**
   * Get is auth route exist
   *
   * @param routePath Route path
   */
  async function getIsAuthRouteExist(routePath: RouteMap[RouteKey]) {
    const routeName = getRouteName(routePath);

    if (!routeName) {
      return false;
    }

    if (authRouteMode.value === 'static') {
      const { authRoutes: staticAuthRoutes } = createStaticRoutes();
      return isRouteExistByRouteName(routeName, staticAuthRoutes);
    }

    const { data } = await fetchIsRouteExist(routeName);

    return data;
  }

  /**
   * Get selected menu key path
   *
   * @param selectedKey Selected menu key
   */
  function getSelectedMenuKeyPath(selectedKey: string) {
    return getSelectedMenuKeyPathByKey(selectedKey, menus.value);
  }

  async function onRouteSwitchWhenLoggedIn() {
    // some global init logic when logged in and switch route
  }

  async function onRouteSwitchWhenNotLoggedIn() {
    // some global init logic if it does not need to be logged in
  }

  async function applyPluginModules(modules: Api.Plugin.PluginFrontendModule[]) {
    resetPluginRoutes();

    if (!modules.length) {
      syncMenus();
      return;
    }

    const pluginMenuList: App.Global.Menu[] = [];
    const cacheNameSet = new Set<RouteKey>(cacheRoutes.value);

    await Promise.all(
      modules.map(async module => {
        if (!module.moduleName) return;
        const moduleInfo = {
          moduleName: module.moduleName,
          pluginId: module.pluginId,
          pluginIsDev: module.pluginIsDev,
          frontDevAddress: module.frontDevAddress
        };
        try {
          await registerPluginLocales(moduleInfo, module.i18n);
          const moduleLoader = await importPluginModule(moduleInfo, module.moduleName);
          const moduleRouters = moduleLoader.router(module.routes || [], module.moduleName);
          const routeMap = new Map<string, RouteRecordRaw>();

          moduleRouters.forEach(routeRecord => {
            const { wrapperRoute, viewRoute, fullPath } = buildPluginRoute(routeRecord);
            const removeFn = router.addRoute(wrapperRoute);
            pluginRouteRemoveFns.push(removeFn);

            if (viewRoute?.name && viewRoute.meta?.keepAlive) {
              cacheNameSet.add(viewRoute.name as RouteKey);
            }

            if (viewRoute?.name) {
              const menuRoute: RouteRecordRaw = { ...viewRoute, path: fullPath };
              routeMap.set(String(viewRoute.name), menuRoute);
            }
          });

          module.menus?.forEach(menu => {
            const matchedRoute = routeMap.get(menu.routeName);
            const menuNode = createPluginMenuNode(matchedRoute, menu);
            if (menuNode) {
              pluginMenuList.push(menuNode);
            }
          });
        } catch (error) {
          console.error('[plugin] load module failed:', module.moduleName, error);
        }
      })
    );

    cacheRoutes.value = Array.from(cacheNameSet);
    pluginMenus.value = pluginMenuList;
    syncMenus();
  }

  let pluginRouteSequence = 0;

  function buildPluginRoute(routeRecord: RouteRecordRaw) {
    const baseName = typeof routeRecord.name === 'string' ? routeRecord.name : `plugin-route-${pluginRouteSequence++}`;
    const layoutKey = (routeRecord.meta?.layout as PluginLayoutKey) || DEFAULT_PLUGIN_LAYOUT;
    const layoutComponent = pluginLayoutComponents[layoutKey] ?? pluginLayoutComponents[DEFAULT_PLUGIN_LAYOUT];
    const fullPath = routeRecord.path || `/${baseName}`;

    const viewRoute: RouteRecordRaw = {
      ...routeRecord,
      path: '',
      meta: {
        ...routeRecord.meta,
        layout: layoutKey
      }
    };

    const wrapperRoute: RouteRecordRaw = {
      path: fullPath,
      name: `${baseName}__layout`,
      component: layoutComponent,
      meta: {
        ...(routeRecord.meta || {}),
        layout: layoutKey
      },
      children: [viewRoute]
    };

    return { wrapperRoute, viewRoute, fullPath };
  }

  function createPluginMenuNode(route: RouteRecordRaw | undefined, menuConfig: Api.Plugin.PluginFrontendMenu) {
    if (!route?.name) {
      return null;
    }

    const menu = getGlobalMenuByBaseRoute({
      name: route.name as RouteKey,
      path: route.path || '',
      meta: route.meta ?? {}
    } as ElegantConstRoute);

    if (menuConfig?.title) {
      menu.label = menuConfig.title;
    }
    if (menuConfig?.i18nKey) {
      menu.i18nKey = menuConfig.i18nKey;
    }
    menu.order = menuConfig?.order ?? menu.order ?? 0;
    const configuredParentKey = menuConfig?.parent?.trim();
    menu.parentKey = configuredParentKey ? configuredParentKey : null;

    return menu;
  }

  function mergeMenus(baseMenuList: App.Global.Menu[], pluginMenuList: App.Global.Menu[]) {
    const clonedMenus = cloneMenus(baseMenuList);
    pluginMenuList.forEach(menu => insertMenuNode(clonedMenus, menu));
    return sortMenuTree(clonedMenus);
  }

  function cloneMenus(source: App.Global.Menu[]): App.Global.Menu[] {
    return source.map(menu => ({
      ...menu,
      children: menu.children ? cloneMenus(menu.children) : undefined
    }));
  }

  function insertMenuNode(tree: App.Global.Menu[], menuNode: App.Global.Menu) {
    const node: App.Global.Menu = {
      ...menuNode,
      children: menuNode.children ? cloneMenus(menuNode.children) : undefined
    };

    if (!menuNode.parentKey) {
      upsertMenuNode(tree, node);
      return;
    }

    const parent = findMenuByKey(tree, menuNode.parentKey);
    if (parent) {
      parent.children = parent.children || [];
      upsertMenuNode(parent.children, { ...node, parentKey: undefined });
      return;
    }

    upsertMenuNode(tree, node);
  }

  function upsertMenuNode(tree: App.Global.Menu[], candidate: App.Global.Menu) {
    const existing = tree.find(menu => menu.key === candidate.key);
    if (existing) {
      mergeMenuNode(existing, candidate);
    } else {
      tree.push(candidate);
    }
  }

  function mergeMenuNode(target: App.Global.Menu, source: App.Global.Menu) {
    target.label = source.label ?? target.label;
    target.i18nKey = source.i18nKey ?? target.i18nKey;
    target.icon = source.icon ?? target.icon;
    target.order = source.order ?? target.order;
    target.routeName = source.routeName ?? target.routeName;
    if (source.children?.length) {
      target.children = target.children || [];
      source.children.forEach(child => insertMenuNode(target.children!, { ...child, parentKey: undefined }));
    }
  }

  function findMenuByKey(tree: App.Global.Menu[], key: string) {
    for (const menu of tree) {
      if (menu.key === key) {
        return menu;
      }
      if (menu.children?.length) {
        const found = findMenuByKey(menu.children, key);
        if (found) {
          return found;
        }
      }
    }
    return null;
  }

  function sortMenuTree(tree: App.Global.Menu[]) {
    return tree
      .slice()
      .sort((next, prev) => (Number(next.order) || 0) - (Number(prev.order) || 0))
      .map(menu => ({
        ...menu,
        children: menu.children ? sortMenuTree(menu.children) : undefined
      }));
  }


  async function registerPluginLocales(
    moduleInfo: {
      pluginId?: string;
      pluginIsDev?: boolean;
      frontDevAddress?: string;
    },
    localeMap?: Record<string, string>
  ) {
    if (!moduleInfo.pluginId || !localeMap) return;
    const entries = Object.entries(localeMap).filter(([, filePath]) => Boolean(filePath));
    if (!entries.length) return;

    const loadedLocales = pluginLocaleLoaded.get(moduleInfo.pluginId) ?? new Set<string>();

    await Promise.all(
      entries.map(async ([locale, filePath]) => {
        if (loadedLocales.has(locale)) return;
        try {
          const url = resolvePluginAssetUrl(moduleInfo, filePath);
          if (!url) return;
          const response = await fetch(url);
          if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
          }
          const messages = await response.json();
          mergeLocaleMessages(locale, messages);
          loadedLocales.add(locale);
        } catch (error) {
          console.error('[plugin] load i18n failed:', moduleInfo.pluginId, locale, error);
        }
      })
    );

    pluginLocaleLoaded.set(moduleInfo.pluginId, loadedLocales);
  }

  function resolvePluginAssetUrl(
    moduleInfo: {
      pluginId?: string;
      pluginIsDev?: boolean;
      frontDevAddress?: string;
    },
    assetPath: string
  ) {
    if (!moduleInfo.pluginId || !assetPath) return '';
    if (/^https?:\/\//i.test(assetPath)) {
      return assetPath;
    }
    const sanitizedPath = assetPath.replace(/^\/+/, '');
    if (moduleInfo.pluginIsDev && moduleInfo.frontDevAddress) {
      const base = moduleInfo.frontDevAddress.replace(/\/$/, '');
      return `${base}/plugin/${moduleInfo.pluginId}/${sanitizedPath}`;
    }

    return `/api/plugin-static/${moduleInfo.pluginId}/${sanitizedPath}`;
  }

  return {
    resetStore,
    routeHome,
    menus,
    searchMenus,
    updateGlobalMenusByLocale,
    cacheRoutes,
    excludeCacheRoutes,
    resetRouteCache,
    breadcrumbs,
    initConstantRoute,
    isInitConstantRoute,
    initAuthRoute,
    isInitAuthRoute,
    setIsInitAuthRoute,
    refreshPluginRoutes,
    getIsAuthRouteExist,
    getSelectedMenuKeyPath,
    onRouteSwitchWhenLoggedIn,
    onRouteSwitchWhenNotLoggedIn
  };
});
