CREATE TABLE IF NOT EXISTS `tool_generator_table` (
  `id` bigint(20) NOT NULL COMMENT 'primary key',
  `table_name` varchar(100) NOT NULL COMMENT 'table name',
  `table_comment` varchar(255) DEFAULT NULL COMMENT 'table comment',
  `table_prefix` varchar(50) DEFAULT NULL COMMENT 'table prefix',
  `plugin_id` varchar(100) NOT NULL COMMENT 'plugin id',
  `plugin_name` varchar(100) NOT NULL COMMENT 'plugin name',
  `version` varchar(32) DEFAULT '1.0.0' COMMENT 'plugin version',
  `parent_package` varchar(200) NOT NULL COMMENT 'parent package',
  `module_name` varchar(100) NOT NULL COMMENT 'module name',
  `route_path` varchar(200) DEFAULT NULL COMMENT 'route path',
  `menu_name` varchar(100) DEFAULT NULL COMMENT 'menu name',
  `i18n_key` varchar(100) DEFAULT NULL COMMENT 'i18n key',
  `icon` varchar(100) DEFAULT NULL COMMENT 'icon',
  `include_table_sql` char(1) DEFAULT '1' COMMENT 'include table sql',
  `parent_menu_id` bigint(20) DEFAULT 0 COMMENT 'parent menu id',
  `author` varchar(100) DEFAULT NULL COMMENT 'author',
  `status` char(1) DEFAULT '1' COMMENT 'status',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `create_user` varchar(50) DEFAULT NULL COMMENT 'create user',
  `update_user` varchar(50) DEFAULT NULL COMMENT 'update user',
  `is_deleted` tinyint(4) DEFAULT 0 COMMENT 'deleted flag',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_table_name` (`table_name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='codegen table';

CREATE TABLE IF NOT EXISTS `tool_generator_table_column` (
  `id` bigint(20) NOT NULL COMMENT 'primary key',
  `table_id` bigint(20) NOT NULL COMMENT 'table id',
  `table_name` varchar(100) NOT NULL COMMENT 'table name',
  `column_name` varchar(100) NOT NULL COMMENT 'column name',
  `property_name` varchar(100) NOT NULL COMMENT 'property name',
  `column_comment` varchar(200) DEFAULT NULL COMMENT 'column comment',
  `data_type` varchar(100) DEFAULT NULL COMMENT 'data type',
  `java_type` varchar(100) DEFAULT NULL COMMENT 'java type',
  `typescript_type` varchar(100) DEFAULT NULL COMMENT 'typescript type',
  `ordinal_position` int(11) DEFAULT NULL COMMENT 'ordinal position',
  `is_i18n` char(1) DEFAULT '1' COMMENT 'i18n',
  `is_required` char(1) DEFAULT '0' COMMENT 'required',
  `is_list` char(1) DEFAULT '0' COMMENT 'list',
  `is_search` char(1) DEFAULT '0' COMMENT 'search',
  `search_type` varchar(32) DEFAULT NULL COMMENT 'search type',
  `is_added` char(1) DEFAULT '0' COMMENT 'add',
  `is_edit` char(1) DEFAULT '0' COMMENT 'edit',
  `dict_code` varchar(100) DEFAULT NULL COMMENT 'dict code',
  `render_type` varchar(32) DEFAULT 'input' COMMENT 'render type',
  `form_disabled` char(1) DEFAULT '0' COMMENT 'form disabled',
  `form_readonly` char(1) DEFAULT '0' COMMENT 'form readonly',
  `min_length` int(11) DEFAULT NULL COMMENT 'min length',
  `max_length` int(11) DEFAULT NULL COMMENT 'max length',
  `min_value` decimal(18,6) DEFAULT NULL COMMENT 'min value',
  `max_value` decimal(18,6) DEFAULT NULL COMMENT 'max value',
  `pattern` varchar(200) DEFAULT NULL COMMENT 'pattern',
  `component_props` text COMMENT 'component props',
  `form_span` int(11) DEFAULT 12 COMMENT 'form span',
  `search_span` int(11) DEFAULT 12 COMMENT 'search span',
  `list_width` int(11) DEFAULT 160 COMMENT 'list width',
  `placeholder` varchar(200) DEFAULT NULL COMMENT 'placeholder',
  `default_value` varchar(200) DEFAULT NULL COMMENT 'default value',
  `status` char(1) DEFAULT '1' COMMENT 'status',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `create_user` varchar(50) DEFAULT NULL COMMENT 'create user',
  `update_user` varchar(50) DEFAULT NULL COMMENT 'update user',
  `is_deleted` tinyint(4) DEFAULT 0 COMMENT 'deleted flag',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_table_id` (`table_id`) USING BTREE,
  INDEX `idx_column_name` (`column_name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='codegen table column';
