plugin:
  id: tt-plugin-wc-vue
  name: WebComponent Vue Demo
  description: Web-Component Vue plugin template for plugin-dev mode
  minimalVersion: 2.2.0
  version: 1.0.0
  staticLocations: /ui/
  isDev: true
  frontDevAddress: http://127.0.0.1:5176
  updateUrl:
author:
  name: tt
  email: 1042731605@qq.com
  webSite: http://localhost
