# mybatis plus 配置
mybatis-plus:
#  mapper-locations: classpath:com/tt/modules/*/repository/mapper/*Mapper.xml
 # typeAliasesPackage: com.izpan.modules.**.domain.entity
  global-config:
    banner: false
    db-config:
      # 主键类型
      id-type: assign_id
      # 字段策略
      insert-strategy: not_null #只插入非NULL字段
      update-strategy: not_null #只更新非NULL字段
      table-underline: true #开启下划线转驼峰：user_name ↔ userName
      logic-delete-field: is_deleted
      # 启用 SQL 保留字自动转义（针对所有表字段）
      escape-symbol: '`'  # MySQL 使用反引号
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    variables:
      wrap_keywords: true  # 自动转义关键字
